# Generated by Django 5.0.6 on 2024-05-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата курса')),
                ('currency_id', models.IntegerField(max_length=10, verbose_name='ID валюты')),
                ('currency_name', models.CharField(max_length=10, verbose_name='Валюта')),
                ('scale', models.IntegerField(verbose_name='Количество')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс')),
            ],
        ),
    ]
